# initial position does not have to be correct if you are not flying with flowdeck or crazyswarm


crazyflies:
- channel: 125
  id: 193
  initialPosition:
  - 0.0
  - 0.0
  - 0.0
  type: default
  
- channel: 125
  id: 194
  initialPosition:
  - 0.5
  - 0.0
  - 0.0
  type: default

- channel: 115
  id: 196
  initialPosition:
  - 0.0
  - 0.5
  - 0.0
  type: default

- channel: 115
  id: 197
  initialPosition:
  - 0.0
  - -0.5
  - 0
  type: default

- channel: 115
  id: 198
  initialPosition:
  - 0.5
  - 0.5
  - 0.0
  type: default

- channel: 105
  id: 199
  initialPosition:
  - 0.5
  - -0.5
  - 0.0
  type: default